
#ifdef __cplusplus
extern "C" {
#endif

/* This file generated by names.awk do not edit! */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
#include "common.h"
#include "tnef_names.h"
char*
get_tnef_name_str(uint16 d)
{
    static char buf[128];
    static char* str;
    switch(d) {
    case attOWNER:
        str="Owner";
        break;
    case attSENTFOR:
        str="Sent For";
        break;
    case attDELEGATE:
        str="Delegate";
        break;
    case attDATESTART:
        str="Date Start";
        break;
    case attDATEEND:
        str="Date End";
        break;
    case attAIDOWNER:
        str="Owner Appointment ID";
        break;
    case attREQUESTRES:
        str="Response Requested.";
        break;
    case attFROM:
        str="From";
        break;
    case attSUBJECT:
        str="Subject";
        break;
    case attDATESENT:
        str="Date Sent";
        break;
    case attDATERECD:
        str="Date Received";
        break;
    case attMESSAGESTATUS:
        str="Message Status";
        break;
    case attMESSAGECLASS:
        str="Message Class";
        break;
    case attMESSAGEID:
        str="Message ID";
        break;
    case attPARENTID:
        str="Parent ID";
        break;
    case attCONVERSATIONID:
        str="Conversation ID";
        break;
    case attBODY:
        str="Body";
        break;
    case attPRIORITY:
        str="Priority";
        break;
    case attATTACHDATA:
        str="Attachment Data";
        break;
    case attATTACHTITLE:
        str="Attachment File Name";
        break;
    case attATTACHMETAFILE:
        str="Attachment Meta File";
        break;
    case attATTACHCREATEDATE:
        str="Attachment Creation Date";
        break;
    case attATTACHMODIFYDATE:
        str="Attachment Modification Date";
        break;
    case attDATEMODIFY:
        str="Date Modified";
        break;
    case attATTACHTRANSPORTFILENAME:
        str="Attachment Transport Filename";
        break;
    case attATTACHRENDDATA:
        str="Attachment Rendering Data";
        break;
    case attMAPIPROPS:
        str="MAPI Properties";
        break;
    case attRECIPTABLE:
        str="Recipients";
        break;
    case attATTACHMENT:
        str="Attachment";
        break;
    case attTNEFVERSION:
        str="TNEF Version";
        break;
    case attOEMCODEPAGE:
        str="OEM Codepage";
        break;
    case attORIGNINALMESSAGECLASS:
        str="Original Message Class";
        break;
    default:
        str=NULL;
        break;
    }
    if ( str )
    {
        sprintf(buf,"%s <%04x>",str,d);
    }
    else
    {
        sprintf(buf,"%04x",d);
    }
    return buf;
}

#ifdef __cplusplus
}
#endif