
#ifdef __cplusplus
extern "C" {
#endif

/* This file generated by names.awk do not edit! */
#ifndef TNEF_NAMES_H
#define TNEF_NAMES_H
enum _tnef_name {
	attOWNER                                      = 0x0000,
	attSENTFOR                                    = 0x0001,
	attDELEGATE                                   = 0x0002,
	attDATESTART                                  = 0x0006,
	attDATEEND                                    = 0x0007,
	attAIDOWNER                                   = 0x0008,
	attREQUESTRES                                 = 0x0009,
	attFROM                                       = 0x8000,
	attSUBJECT                                    = 0x8004,
	attDATESENT                                   = 0x8005,
	attDATERECD                                   = 0x8006,
	attMESSAGESTATUS                              = 0x8007,
	attMESSAGECLASS                               = 0x8008,
	attMESSAGEID                                  = 0x8009,
	attPARENTID                                   = 0x800a,
	attCONVERSATIONID                             = 0x800b,
	attBODY                                       = 0x800c,
	attPRIORITY                                   = 0x800d,
	attATTACHDATA                                 = 0x800f,
	attATTACHTITLE                                = 0x8010,
	attATTACHMETAFILE                             = 0x8011,
	attATTACHCREATEDATE                           = 0x8012,
	attATTACHMODIFYDATE                           = 0x8013,
	attDATEMODIFY                                 = 0x8020,
	attATTACHTRANSPORTFILENAME                    = 0x9001,
	attATTACHRENDDATA                             = 0x9002,
	attMAPIPROPS                                  = 0x9003,
	attRECIPTABLE                                 = 0x9004,
	attATTACHMENT                                 = 0x9005,
	attTNEFVERSION                                = 0x9006,
	attOEMCODEPAGE                                = 0x9007,
	attORIGNINALMESSAGECLASS                      = 0x9008,
};
typedef enum _tnef_name tnef_name;
extern char*
get_tnef_name_str(uint16 d);


#ifdef __cplusplus
}
#endif
#endif /* TNEF_NAMES_H */
