
#ifdef __cplusplus
extern "C" {
#endif

/* This file generated by names.awk do not edit! */
#ifndef TNEF_TYPES_H
#define TNEF_TYPES_H
enum _tnef_type {
	szTRIPLES                                     = 0x0000,
	szSTRING                                      = 0x0001,
	szTEXT                                        = 0x0002,
	szDATE                                        = 0x0003,
	szSHORT                                       = 0x0004,
	szLONG                                        = 0x0005,
	szBYTE                                        = 0x0006,
	szWORD                                        = 0x0007,
	szDWORD                                       = 0x0008,
	szMAX                                         = 0x0009,
};
typedef enum _tnef_type tnef_type;
extern char*
get_tnef_type_str(uint16 d);


#endif /* TNEF_TYPES_H */

#ifdef __cplusplus
}
#endif