# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

int_read_msg <- function(path) {
    .Call('_msgxtractr_int_read_msg', PACKAGE = 'msgxtractr', path)
}

