# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Is a sequence of raw bytes an RTF document?
#'
#' @param v a raw vector
#' @export
is_rtf <- function(v) {
    .Call(`_msgxtractr_is_rtf`, v)
}

#' Decode RTF from a raw vector
#'
#' @param v a raw vector
#' @export
decode_rtf <- function(v) {
    .Call(`_msgxtractr_decode_rtf`, v)
}

int_read_msg <- function(path) {
    .Call(`_msgxtractr_int_read_msg`, path)
}

